[package]
name = "test_suite"
version = "0.1.0"
edition = "2021"
authors = ["Ed Smith <ed.smith@collabora.com>"]
publish = false
license = "Apache-2.0 OR MIT"

[dependencies]
persian-rug = { path = "../persian-rug", features=["clone-replace"] }
clone-replace = "0.1"